---
title: "Explore and Mine Data"
output: html_notebook
---


```{r}
library(ggplot2)
library(RMySQL)
library(RSQLite)

host <- "sql9.freemysqlhosting.net"
username <- "sql9637087"
password <- "F5WLHRRTXU"
dbname <- "sql9637087"

mydbcon <- dbConnect(
  MySQL(),
  user = username,
  password = password,
  dbname = dbname,
  host = host
)
```


```{r}
top_five_reps_per_year <- "
  SELECT year, firstName, lastName, SUM(total_sold) AS total_sales
  FROM rep_facts
  GROUP BY year, firstName, lastName
  ORDER BY year, total_sales DESC
  LIMIT 5;
"

top_five_reps_per_quarter <- "
  SELECT quarter, firstName, lastName, SUM(total_sold) AS total_sales
  FROM rep_facts
  GROUP BY quarter, firstName, lastName
  ORDER BY quarter, total_sales DESC;
"

total_sold_per_year <- "
  SELECT year, SUM(total_sold) AS total_sold_per_year
  FROM product_facts
  GROUP BY year;
"

total_sold_per_month <- "
  SELECT month, SUM(total_sold) AS total_sold_per_month
  FROM product_facts
  GROUP BY month;
"

total_sold_per_quarter <- "
  SELECT quarter, SUM(total_sold) AS total_sold_per_quarter
  FROM product_facts
  GROUP BY quarter;
"

top_five_reps_per_year.df <- dbGetQuery(mydbcon, top_five_reps_per_year)
top_five_reps_per_quarter.df <- dbGetQuery(mydbcon, top_five_reps_per_quarter)
total_sold_per_year.df <- dbGetQuery(mydbcon, total_sold_per_year)
total_sold_per_quarter.df <- dbGetQuery(mydbcon, total_sold_per_quarter)
total_sold_per_month.df <- dbGetQuery(mydbcon, total_sold_per_month)
```

```{r}
print(top_five_reps_per_quarter.df)
```

```{r}
library(scales)

ggplot(top_five_reps_per_year.df, aes(x = year, y = total_sales, fill = paste(firstName, lastName))) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Year", y = "Total Sales", title = "Top 5 Sales Reps - Total Sales per Year", fill = "Sales Rep") +
  theme_minimal() +
  scale_y_continuous(labels = comma) 
```

```{r}
ggplot(top_five_reps_per_quarter.df, aes(x = quarter, y = total_sales, color = paste(firstName, lastName))) +
  geom_line() +
  geom_point() +
  labs(x = "Quarter", y = "Total Sales", title = "Top Sales Reps - Total Sales per 2020 Quarter", color = "Sales Rep") +
  theme_minimal()
```

```{r}
ggplot(total_sold_per_year.df, aes(x = year, y = total_sold_per_year)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Total Sold", title = "Total Sold per Year") +
  theme_minimal()
```

```{r}
ggplot(total_sold_per_quarter.df, aes(x = quarter, y = total_sold_per_quarter)) +
  geom_line() +  # This adds the line connecting plot points
  geom_point() +
  labs(x = "Quarter", y = "Total Sold", title = "Total Sold per Quarter") +
  theme_minimal()
```

```{r}
ggplot(total_sold_per_month.df, aes(x = month, y = total_sold_per_month)) +
  geom_line() +  # This adds the line connecting plot points
  geom_point() +
  labs(x = "Month", y = "Total Sold", title = "Total Sold per Month") +
  theme_minimal()
```

```{r}
dbDisconnect(mydbcon)
```